<div class="right-title-2">
<center><h3>{{trans('words.most_popular')}}</h3></center>
</div>
<div class="row most">
<div class="col-xs-4"><a href="{{url('movies',['lang'=>$lang,'id'=>22,'name'=>str_replace(' ', '-','Fantastic Four')])}}">{{ Html::image("movies-images/1469636582.jpg","Fantastic Four", array('style'=>'max-height:135px;min-height:135px','title' => 'Fantastic Four','class'=>'img-responsive')) }}</a></div>
<div class="col-xs-4"><a href="{{url('movies',['lang'=>$lang,'id'=>5,'name'=>str_replace(' ', '-','Avengers: Age of Ultron')])}}">{{ Html::image("movies-images/1469574784.jpg","Avengers: Age of Ultron", array('style'=>'max-height:135px;min-height:135px','title' => 'Avengers: Age of Ultron','class'=>'img-responsive')) }}</a></div>
<div class="col-xs-4"><a href="{{url('movies',['lang'=>$lang,'id'=>10,'name'=>str_replace(' ', '-','Fast & Furious 7')])}}">{{ Html::image("movies-images/1469583960.jpg","Fast & Furious 7", array('style'=>'max-height:135px;min-height:135px','title' => 'Fast & Furious 7','class'=>'img-responsive')) }}</a></div>
<div class="col-xs-4"><a href="{{url('movies',['lang'=>$lang,'id'=>20,'name'=>str_replace(' ', '-','Mission Impossible Rogue Nation')])}}">{{ Html::image("movies-images/1469629346.jpg","Mission Impossible Rogue Nation", array('style'=>'max-height:135px;min-height:135px','title' => 'Mission Impossible Rogue Nation','class'=>'img-responsive')) }}</a></div>
<div class="col-xs-4"><a href="{{url('movies',['lang'=>$lang,'id'=>24,'name'=>str_replace(' ', '-','The Transporter Refueled')])}}">{{ Html::image("movies-images/1469637604.jpg","The Transporter Refueled", array('style'=>'max-height:135px;min-height:135px','title' => 'The Transporter Refueled','class'=>'img-responsive')) }}</a></div>
<div class="col-xs-4"><a href="{{url('movies',['lang'=>$lang,'id'=>2,'name'=>str_replace(' ', '-','THE SHAWSHANK REDEMPTION')])}}">{{ Html::image("movies-images/1469546784.jpg","THE SHAWSHANK REDEMPTION", array('style'=>'max-height:135px;min-height:135px','title' => 'THE SHAWSHANK REDEMPTION','class'=>'img-responsive')) }}</a></div>
<div class="col-xs-4"><a href="{{url('movies',['lang'=>$lang,'id'=>4,'name'=>str_replace(' ', '-','Ice Age: Collision Course')])}}">{{ Html::image("movies-images/1469561295.jpg","Ice Age: Collision Course", array('style'=>'max-height:135px;min-height:135px','title' => 'Ice Age: Collision Course','class'=>'img-responsive')) }}</a></div>
<div class="col-xs-4"><a href="{{url('movies',['lang'=>$lang,'id'=>7,'name'=>str_replace(' ', '-','Jurassic World')])}}">{{ Html::image("movies-images/1469581975.jpg","Jurassic World", array('style'=>'max-height:135px;min-height:135px','title' => 'Jurassic World','class'=>'img-responsive')) }}</a></div>
<div class="col-xs-4"><a href="{{url('movies',['lang'=>$lang,'id'=>12,'name'=>str_replace(' ', '-','Terminator Genisys')])}}">{{ Html::image("movies-images/1469584888.jpg","Terminator Genisys", array('style'=>'max-height:135px;min-height:135px','title' => 'Terminator Genisys','class'=>'img-responsive')) }}</a></div>
</div>